FROM node:16-slim

# Set the working directory inside the container
WORKDIR /app

# Copy only package.json and package-lock.json first to install dependencies
COPY ./package*.json /app/

# Install the npm dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

# Now check if we can build after installing dependencies
CMD ["npm", "run", "dev"]
