# Generated by Django 5.1.4 on 2024-12-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_image_editedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedimage',
            name='image_mask',
        ),
    ]
