# Generated by Django 5.1.4 on 2024-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imagev2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageV3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('mask_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='imagev2',
            name='rmbg_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
