# Generated by Django 5.1.4 on 2024-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imagev3_alter_imagev2_rmbg_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageV2',
        ),
        migrations.DeleteModel(
            name='ImageV3',
        ),
        migrations.AddField(
            model_name='editedimage',
            name='image_mask',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
