version: "3.8"
services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - DEBUG=1
    depends_on:
      - db

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_db_name
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: